### ISSUE TITLE
Building One Must Fall + Raptor for Windows for ARM?

### ISSUE THREAD

**Issue by exocyt0sis** [mijk84/win-arm64-binaries#1]
Thanks for doing all of this. Would it be doable to build [One Must Fall](https://github.com/omf2097/openomf) and [Raptor: Call  of the Shadows](https://github.com/skynettx/raptor) for Windows for ARM?

**Comment by mijk84** [comment]
https://github.com/mijk84/win-arm64-binaries/releases/tag/openomf

**Comment by mijk84** [comment]
I wasn't able to compile Raptor from that git repo. It's possible that another source may work. I'll keep an eye out.

**Comment by exocyt0sis** [comment]
> https://github.com/mijk84/win-arm64-binaries/releases/tag/openomf

Excellent! Please add any changes you've made to the official OpenOMF repository, if you don't mind. That way, they'll likely trickle down to the official releases! 👍

**Comment by mijk84** [comment]
Closing as Raptor is not compiling as of yet.
