### ISSUE TITLE
How this repo works?

### ISSUE THREAD

**Issue by michelepagot** [mijk84/win-arm64-binaries#3]
Seems in the repo there's only a README but many releases from other projects...

**Comment by mijk84** [comment]
They are compiled packages that are native Windows ARM64 binaries.

**Comment by michelepagot** [comment]
Many thanks for your repo and effor. The README is indeed pretty clear about "what" they are. 
My curiosity was more oriented to figure out how they are build, which toolchain has been used, which steps and commands are needed, which external deependency are needed, who build it: is a github pipeline, where the source come from ?

**Comment by mijk84** [comment]
I build using MSYS2/ClangARM64. I will sometimes modify a bit of code in order for things to compile on ARM64 but usually nothing more than that. If it fails and I can't find a way to resolve the issue, I move on to the next project. This is a hobby by me and I do all the compiling.
