### ISSUE TITLE
fixed release tags (newest build only)

### ISSUE THREAD

**Issue by ArminiusTux** [mijk84/win-arm64-binaries#5]
Dear @mijk84 ,

First let me thank you for providing (and resuming) ARM64 builds for Windows!
Aside from Linaro there weren't many WinARM64 pioneers, who provided open source builds to the community.
Your builds also gave me inspiration to start releasing some myself, approx. a year ago.

Would you consider changing your release tag scheme?

The latest build of any programme you release would always have a fixed tag:
e.g. https://github.com/mijk84/win-arm64-binaries/releases/tag/qemu
{old releases would have to be renamed to e.g. https://github.com/mijk84/win-arm64-binaries/releases/tag/qemu-9.0.3}

Although this introduces an additional step for every release on your part, it would always lead to the latest build for "consumers" visiting:

[https://armrepo.ver.lt/](url)

and obviously would eliminate the need to modify the URLs for every new build version for the project's contributors.

Best regards,

ArminiusTux

**Comment by mijk84** [comment]
Thanks! I've noticed your builds as well. That's great to hear! I'm a github noob. I'm just playing by ear. I'm certainly willing to clean up how to release builds if it's asked of me

**Comment by ArminiusTux** [comment]
Splendid, lets ask @talynone, who posted your latest releases, on his take.
Maybe he is fine with the way it is and no change is needed after all. 😉

**Comment by mijk84** [comment]
Where was this posted? I noticed that EmuGen has some of my releases but they are the old ones. It's fine, I made an update to the page to make sure that my github page is in the links.

 I'm happy to learn to do things differently, or properly if you will, I'm not upset at all.

**Comment by ArminiusTux** [comment]
Well @talynone pulls the requests, but [the commits](https://github.com/arminask/windows-arm-apps/commits/main/?author=jgershgorin) are made by his alter ego @jgershgorin 😜(most likely his second github account). 




> I'm happy to learn to do things differently, or properly if you will, I'm not upset at all.

Good to hear, let me explain my method a bit further then.

When I released Flycast v2.3-dev a couple of days ago it used the release tag "**flycast**"
[flycast-current build](https://github.com/ArminiusTux/WinARM64-binaries/releases/tag/flycast)


After version 2.4 came out, I simply renamed the tag on the old release to "**flycast_2.3.2-dev**" thus freeing the tag for version 2.4
[flycast-old build](https://github.com/ArminiusTux/WinARM64-binaries/releases/tag/flycast_2.3.2-dev)



This way any links from https://armrepo.ver.lt/?search=Flycast or https://emulation.gametechwiki.com/index.php/Emulators_on_Windows/ARM

always point to the latest (build) version and there is no need to update the URLs on the external websites.

**Comment by talynone** [comment]
Yeah, it would be nice to have a consistent link to the  latest build of a particular release. That way I don't have manually check every once in a while if a new version with a new github release link needs to be updated on the app list.

**Comment by mijk84** [comment]
I fixed the tags
